### ISSUE TITLE
Addonbrowser scrolling

### ISSUE THREAD

**Issue by frodo19** [b-jesch/skin.estuary.modv2#128]
Hi jesch, 
when we scroll down or up in the all addons page, the scrolling not smooth, stuttering, or stuck. 
If the addons has fanart , and the skin trying to display those fanarts during scrolling, come the stuttering. 
Maybe just minor thing, but I not see that in movies, with fanarts, with same widelist view.

Just go to addons, my addons page, and release the down button on the remote continuously.
Made the same in movies, in the same widelist setting, there is no stuttering.
I'v set the fanart opacity to 95%, but that visible in other settings too..
Thanks

**Comment by b-jesch** [comment]
Hi frodo19,

I can not observe this behavior. The addon browser uses the same list (fixed list id 55, view_55_widelist.xml) and the same scrollbar (id 531 from common scrollbars in includes.xml) as the movie views (MyVideoNav.xml) does. So there couldn't be a difference in behaviour between them because there is no difference in code.

Maybe your system is limited by CPU power or network connections. On my development equipment (i7) there is indeed no difference. On a Tanix TX3 (Android S905x3 system) the behaviour is like you described - but this is completely gone when background images are disabled in skin settings. So I think this is a limitation by hardware.

**Comment by frodo19** [comment]
> Hi frodo19,
> 
> I can not observe this behavior. The addon browser uses the same list (fixed list id 55, view_55_widelist.xml) and the same scrollbar (id 531 from common scrollbars in includes.xml) as the movie views (MyVideoNav.xml) does. So there couldn't be a difference in behaviour between them because there is no difference in code.
> 
> Maybe your system is limited by CPU power or network connections. On my development equipment (i7) there is indeed no difference. On a Tanix TX3 (Android S905x3 system) the behaviour is like you described - but this is completely gone when background images are disabled in skin settings. So I think this is a limitation by hardware.

Yes, in windows no issue there, but in firestick, shield tv pro, or atv boxes or coreelec boxes there is a different. When that not fixable, the I can live with it of course.  thanks anyway

**Comment by b-jesch** [comment]
No problem. I have some devices running LibreElec on x86 systems (Intel J3455, J4205, J5005, all ~10W TDP SoC) with no issues too. They have just enough power.

**Comment by frodo19** [comment]
Thanks for read..

**Comment by b-jesch** [comment]
I have reorganized and centralized some code that's handling the background assignment - because that seems the reason for the stuttering behaviour. Maybe you check that? Just uploaded to Git (Nexus)

**Comment by b-jesch** [comment]
I can confirm now that the scrolling is much smoother now on my Android device.
