### ISSUE TITLE
Favorites Keyboard Shortcut

### ISSUE THREAD

**Issue by mmanuxx** [b-jesch/skin.estuary.modv2#156]
I have assigned a keyboard shortcut for my favorites via the keymap editor addon. It does not work with this skin v.18 on Win 11. It works with all other skins I`ve installed.

**Comment by b-jesch** [comment]
The keyboard shortcut addon needs an update. Since Kodi Nexus there is no Favourites Window anymore, this is called now FavouritesBrowser: https://forum.kodi.tv/showthread.php?tid=363553&pid=3118497#pid3118497

Open .kodi/userdata/keymaps/gen.xml and change the occurences of "favourites" against "favouritesbrowser" and restart Kodi.

**Comment by b-jesch** [comment]
Confirmed.

**Comment by mmanuxx** [comment]
Thanks for the info/tip. Works as described.
