### ISSUE TITLE
question feature request  category and stacked widgets

### ISSUE THREAD

**Issue by Mahava** [b-jesch/skin.estuary.modv2#159]
Any plans to add these?

**Comment by b-jesch** [comment]
I'm not familiar with stacked widgets.

**Comment by Mahava** [comment]
You know, like the ones implimented in Arctic Fuse and Arctic Horizon skins.   They're category widgets that display a different widget whenever the category is focused without on click.

**Comment by b-jesch** [comment]
Content/database related widgets are already there so an adaption seems possible.But other menu items would breake the stacked widget design completely such as timers, program guides, tv/radio stations and customized settings in some main menu widgets and addons. They all has to redesigned completely.

Too much work. In this case it's better to create a complete new skin - or using an existing one - instead of modifying an Estuary looking/modded skin.

**Comment by b-jesch** [comment]
The DSTV mod may fulfill your wishes: https://forum.kodi.tv/showthread.php?tid=371037
